### ISSUE TITLE
Exception: Cannot read property 'methodName' of null

### ISSUE THREAD

**Issue by hexadecy** [Gainsight/px-react-native-sdk#15]
Android: 9, 10, 11 and 13
react-native-gainsight-px: 1.9.0
react-native: 0.71.7

From Firebase Crashlytics:
```
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: Cannot read property 'methodName' of null
       at .createError(address at index.android.bundle:1:4112559)
       at .anonymous(address at index.android.bundle:1:4112538)
       at .tryCallOne(InternalBytecode.js:53:16)
       at .anonymous(InternalBytecode.js:139:27)
       at .apply((native):0:0)
       at .anonymous(address at index.android.bundle:1:238172)
       at ._callTimer(address at index.android.bundle:1:237118)
       at ._callReactNativeMicrotasksPass(address at index.android.bundle:1:237283)
       at .callReactNativeMicrotasks(address at index.android.bundle:1:239271)
       at .__callReactNativeMicrotasks(address at index.android.bundle:1:141552)
       at .anonymous(address at index.android.bundle:1:140642)
       at .__guard(address at index.android.bundle:1:141393)
       at .flushedQueue(address at index.android.bundle:1:140553)
       at .invokeCallbackAndReturnFlushedQueue(address at index.android.bundle:1:140496)
```

I'm suspecting this line:
https://github.com/Gainsight/px-react-native-sdk/blob/759f0eb4a104a64798df809ebafe62d5320fd925/lib/GainsightPX.js#L123

**Comment by hexadecy** [comment]
I was sending undefined event to Gainsight.
